export const formStyles = (screenWidth: number) => ({
  requestTypeSelector: {
    flexDirection: "row",
    backgroundColor: "#f1f5f9",
    borderRadius: 12,
    padding: 4,
    marginBottom: 20,
  },
  requestTypeButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: "center",
  },
  requestTypeButtonActive: {
    backgroundColor: "#fff",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  requestTypeButtonText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#64748b",
  },
  requestTypeButtonTextActive: {
    color: "#2563eb",
    fontWeight: "600",
  },
  formSection: {
    gap: 16,
  },
  formLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#374151",
    marginBottom: 4,
  },
  pickerContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 12,
    padding: 16,
  },
  pickerText: {
    fontSize: 14,
    color: "#0f172a",
    fontWeight: "500",
  },
  leaveTypeOptions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  leaveTypeOption: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: "#f1f5f9",
    borderRadius: 8,
  },
  leaveTypeOptionActive: {
    backgroundColor: "#2563eb",
  },
  leaveTypeOptionText: {
    fontSize: 12,
    fontWeight: "500",
    color: "#64748b",
  },
  leaveTypeOptionTextActive: {
    color: "#fff",
  },
  dateRow: {
    flexDirection: "row",
    gap: 12,
  },
  dateInputContainer: {
    flex: 1,
  },
  dateInput: {
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 12,
    padding: 16,
  },
  dateInputText: {
    fontSize: 14,
    color: "#0f172a",
    fontWeight: "500",
  },
  timeInputContainer: {
    flex: 1,
  },
  timeInput: {
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 12,
    padding: 16,
  },
  timeInputText: {
    fontSize: 14,
    color: "#0f172a",
    fontWeight: "500",
  },
  textInput: {
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 12,
    padding: 16,
    fontSize: 14,
    color: "#0f172a",
  },
  textArea: {
    height: 100,
    textAlignVertical: "top",
  },
  durationHint: {
    fontSize: 12,
    color: "#64748b",
    marginTop: 4,
  },
  permissionTypeGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  permissionTypeButton: {
    width: (screenWidth - 80) / 2,
    alignItems: "center",
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 12,
    padding: 16,
    gap: 8,
  },
  permissionTypeButtonActive: {
    backgroundColor: "#dbeafe",
    borderColor: "#2563eb",
  },
  permissionTypeIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
  },
  permissionTypeIconActive: {
    backgroundColor: "#2563eb15",
  },
  permissionTypeText: {
    fontSize: 12,
    fontWeight: "500",
    color: "#64748b",
    textAlign: "center",
  },
  permissionTypeTextActive: {
    color: "#2563eb",
    fontWeight: "600",
  },
  durationOptions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  durationOption: {
    flex: 1,
    paddingVertical: 12,
    backgroundColor: "#f1f5f9",
    borderRadius: 8,
    alignItems: "center",
  },
  durationOptionActive: {
    backgroundColor: "#2563eb",
  },
  durationOptionText: {
    fontSize: 12,
    fontWeight: "500",
    color: "#64748b",
  },
  durationOptionTextActive: {
    color: "#fff",
  },
  quickHours: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  quickHourButton: {
    flex: 1,
    paddingVertical: 10,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 8,
    alignItems: "center",
  },
  quickHourText: {
    fontSize: 12,
    color: "#64748b",
  },
  quickMinutes: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  quickMinuteButton: {
    flex: 1,
    paddingVertical: 10,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 8,
    alignItems: "center",
  },
  quickMinuteText: {
    fontSize: 12,
    color: "#64748b",
  },
  forgotTypeSelector: {
    flexDirection: "row",
    backgroundColor: "#f1f5f9",
    borderRadius: 12,
    padding: 4,
    gap: 4,
  },
  forgotTypeButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  forgotTypeButtonActive: {
    backgroundColor: "#fff",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  forgotTypeButtonText: {
    fontSize: 12,
    fontWeight: "500",
    color: "#64748b",
  },
  forgotTypeButtonTextActive: {
    color: "#2563eb",
    fontWeight: "600",
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  sectionHeaderText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#374151",
  },
  recipientDropdownMenu: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 12,
    paddingVertical: 8,
    marginTop: 4,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    maxHeight: 200,
  },
  recipientDropdownItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
  },
  checkboxContainer: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: "#cbd5e1",
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxActive: {
    borderColor: "#2563eb",
    backgroundColor: "#2563eb",
  },
  checkboxActiveLocked: {
    borderColor: "#1f2937",
    backgroundColor: "#1f2937",
  },
  checkboxInner: {
    width: 8,
    height: 8,
    backgroundColor: "#fff",
    borderRadius: 2,
  },
  recipientNameText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#1e293b",
  },
  recipientEmailText: {
    fontSize: 12,
    color: "#64748b",
  },
  lockedCcText: {
    fontSize: 11,
    color: "#64748b",
    marginLeft: 6,
  },
  lockedCcTextBlue: {
    fontSize: 11,
    color: "#2563eb",
    fontWeight: "500",
    marginLeft: 6,
  },
  roleBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: "#f1f5f9",
    borderRadius: 4,
  },
  roleBadgeText: {
    fontSize: 11,
    color: "#475569",
  },
  lockedIconContainer: {
    position: "absolute",
    top: -4,
    right: -4,
    backgroundColor: "#fff",
    borderRadius: 6,
  },
  errorText: {
    fontSize: 12,
    color: "#ef4444",
    marginTop: 8,
  },
  selectedPillsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
  },
  selectedPillTo: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#dbeafe",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    gap: 6,
  },
  selectedPillTextTo: {
    fontSize: 12,
    color: "#1d4ed8",
  },
  selectedPillCc: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f3f4f6",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    gap: 6,
  },
  selectedPillTextCc: {
    fontSize: 12,
    color: "#374151",
  },
});
